; flashrom serprog programmer for ESP32 / ESP8266
[env]
framework = arduino
monitor_speed = 921600
upload_speed = 460800

[env:esp32]
platform = espressif32
board = esp32dev

[env:esp8266]
platform = espressif8266
board = nodemcuv2
